
project_id = "89be5c80-2fa9-4ce0-88dc-2475aa328e36"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[functions.mercado-pago-checkout]
verify_jwt = true
