// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syorwftoivcqwugvfazj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5b3J3ZnRvaXZjcXd1Z3ZmYXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTIwNjksImV4cCI6MjA2NzEyODA2OX0.2wHvETxQzb6A5KPYh1DM9cZhRDh18zkjjzRWLU28xac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});